sudo: required
services: 
  - docker

before_install:
  - docker build -t izardasa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run izardasa/react-test npm test -- --coverage

after_success:
  - docker build -t izardasa/multi-client ./client
  - docker build -t izardasa/multi-nginx ./nginx
  - docker build -t izardasa/multi-server ./server
  - docker build -t izardasa/multi-worker ./worker

  #login into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take those images and push them to docker hub
  - docker push izardasa/multi-client
  - docker push izardasa/multi-nginx
  - docker push izardasa/multi-server
  - docker push izardasa/multi-worker