sudo: required
services: 
  - docker

before_install:
  - docker build -t sanjayiz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sanjayiz/react-test npm test 

after_success:
  - docker build -t sanjayiz/multi-client ./client
  - docker build -t sanjayiz/multi-nginx ./nginx
  - docker build -t sanjayiz/multi-server ./server
  - docker build -t sanjayiz/multi-worker ./worker

  #login into the docker cli
  - echo "$password"" | docker login -u "$user" --password-stdin docker.io

  #take those images and push them to docker hub
  - docker push sanjayiz/multi-client
  - docker push sanjayiz/multi-nginx
  - docker push sanjayiz/multi-server
  - docker push sanjayiz/multi-worker